name: Build and test software

on:
  push:
    branches:
      - main

jobs:
  build_and_test_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install Pillow requests pyinstaller pyautogui

    - name: Build for Windows
      run: |
        pyinstaller --onefile --noconsole --icon=assets/view_earth.ico --distpath=. Heroes3MapLiker.py

    - name: Run Windows Tests
      run: python tests.py

  build_and_test_macos:
    needs: build_and_test_windows  # Wait for Windows job to complete successfully
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install Pillow requests pyinstaller pyautogui

    - name: Build for macOS
      run: |
        pyinstaller --onefile --noconsole --icon=assets/view_earth.ico --distpath=. Heroes3MapLiker.py

    - name: Run macOS Tests
      run: python tests.py

  build_and_test_linux:
    needs: build_and_test_macos  # Wait for macOS job to complete successfully
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get install python3-tk
        pip install Pillow requests pyinstaller pyautogui

    - name: Build for Linux
      run: |
        pyinstaller --onefile --noconsole --icon=assets/view_earth.ico --distpath=. Heroes3MapLiker.py

    - name: Run Linux Tests
      run: python tests.py

    - name: Commit changes # if all tests pass then push changes
      if: ${{ job.status == 'success' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "CI: Automated commit after successful tests"
        git push
